global:
  deploymentVersion: 2
  flinkVersion: v1_14
  image: gimral/beam-app:1.0.5
  jobManager:
    replicas: 1
    resource:
      memory: "1024m"
      cpu: 0.25
  taskManager:
    numberOfTaskSlots: "1"
    resource:
      memory: "2048m"
      cpu: 0.25

  # job:
  #     jarURI: local:///opt/flink/usrlib/beam-app-bundled-1.0.0.jar
  #     entryClass: org.example.kafkaoffset.NoKafkaOperatorApp
  #     #fasterCopy needs to be set in the application
  #     args: 
  #       - --runner=FlinkRunner
  #       - --kafkaBrokers=kafka-cp-kafka.kafka.svc.cluster.local:9092
  #       - --checkpointingInterval=10000
  #     parallelism: 1
  #     upgradeMode: savepoint
  #     state: running
  #     savepointTriggerNonce: 0