apiVersion: flink.apache.org/v1alpha1
kind: FlinkSessionJob
metadata:
  name: beam-app-uae-session-job
spec:
  clusterId: beam-session-cluster
  job:
    jarURI: file:///opt/flink/examples/streaming/StateMachineExample.jar
    parallelism: 1
    upgradeMode: stateless